# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e88e4da90b8de3fc1e2d2e3d37ab8e28cd8dd02b341c4ad88de8a10169567661c46d3f1429b3ce8ae22289274f1e93b9fed90dc8ddba72c9b23f8342b6c93f28

test:
  secret_key_base: bec9c6dfa1f2ced0f21a6c8a95fa5d6d89f31d6cd6308aec070b51a87980d1390c0dcfe716323febe49a0bf3b42a6e20e4f353bd09b308cbb35b61d611d69097

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
